name: 'Runs command and stores outputs'
description: ''
inputs:
  working-directory:
    description: 'working dir'
    required: false
  script:
    description: 'bash script to execute'
    required: true
outputs:
  stdout:
    description: 'stdout'
  stderr:
    description: 'stderr'
  exit:
    description: 'exit code'
  success:
    description: 'if script exited with zero'
runs:
  using: 'node16'
  main: 'dist/index.js'
