name: CI
on: push

jobs:
  test-run:
    defaults:
      run: 
        working-directory: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: 16
    - run: npm install
    - run: npm test
  test-report:
    defaults:
      run: 
        working-directory: report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: 16
    - run: npm install
    - run: npm test