name: integration test run
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: ./run
      id: test
      with:
        script: |
          echo "Testing action"
          ls -lh
    - run: |
       echo "out: ${{ steps.test.outputs.stdout }}"
    